<<<<<<< HEAD
title:  Hoiblog
subtitle: Shuenhoy's Blog
manage:
  type: github
  user: Shuenhoy
  repo: the_test_blog
  version: 1
  always: true

routes:
  post: "#!/post/:name"
  page: "#!/:name"
=======
title:  Hoiblog
subtitle: Shuenhoy's Blog
manage:
  type: github
  user: Shuenhoy
  repo: the_test_blog
  version: 1
  always: true

routes:
  post: "#!/post/:name"
  page: "#!/:name"
>>>>>>> 2e6ecbd97bf602521fdb4b9848a9524c635aabad
